### ISSUE TITLE
water disappearing at Y 0

### ISSUE THREAD

**Issue by himtimfim** [Felicis/Water-Physics-Overhaul#17]
Water disappears when it goes below y 0. this is probably happening because the original mod for 1.16.5, and in 1.16.5 the bottom of the world is at y 0 but in the new update it was extended to go into the negatives.

**Comment by xJiggo** [comment]
There is already a post about this #4

**Comment by Felicis** [comment]
> There is already a post about this #4
yeah, I will close the issue
