### ISSUE TITLE
Moss carpet does't get destroyed by water

### ISSUE THREAD

**Issue by djmrFunnyMan** [Felicis/Water-Physics-Overhaul#26]
All other carpets get destroyed by water except the moss carpet.
![2023-06-26_14 24 38](https://github.com/Felicis/Water-Physics-Overhaul/assets/68905776/54d6edda-3a63-4e98-b900-ee86de7dc26c)

**Comment by Felicis** [comment]
curious... are they destroyed with water in vanilla?
btw: I have yet to tackle correct block destruction, so there will be discussions about this later. I will close this for now

**Comment by djmrFunnyMan** [comment]
> curious... are they destroyed with water in vanilla?

Yes, they are destroyed with water just like other carpets.

The only difference afaik is that the moss carpet isn't flammable
