### ISSUE TITLE
Waterlogged dripstone is an infinite water source

### ISSUE THREAD

**Issue by djmrFunnyMan** [Felicis/Water-Physics-Overhaul#27]
Out of all the bugged waterlogging interactions the dripstone behaves the weirdest
1. Get's waterlogged by 1 packet (so 1 packet gets converted to 8)
2. The created packets flow out of the dripstone
3. The created packets waterlog it again (repeating step 1)
![2023-06-26_14 29 41](https://github.com/Felicis/Water-Physics-Overhaul/assets/68905776/bbfd7f29-d6f0-4d30-b4a5-badae8903bf7)

**Comment by Felicis** [comment]
this is not unexpected and related to #2. It will be fixed once the waterlogging fixes are upgraded to this version. I will close the issue for now. If dripstones are still broken after fixing the waterlogging let me know :+1:
