### ISSUE TITLE
Add water life cycle

### ISSUE THREAD

**Issue by wycats0** [Felicis/Water-Physics-Overhaul#35]
Can you add a water life cycle? in other words that the lakes fill up when is raining, and that the seawater vaporise sometimes creating new clouds.
Also, can you upgrade this mod to 1.20 version?

**Comment by xJiggo** [comment]
Bug fixes are the main priority at the moment. When the tasks are done this may be done check out here #2

**Comment by Felicis** [comment]
Exactly, water life cycle is something I'd like to add, but I haven't had time yet and bugs are more important. As to 1.20 it'll have to wait until I get a better laptop (I can't really run 1.19+ without performance mods)
