### ISSUE TITLE
Older Versions Compatibility

### ISSUE THREAD

**Issue by thecrafting** [Felicis/Water-Physics-Overhaul#36]
Hi ! I really appreciate ur mod ! But, I principaly play on 1.12.2 and i'm not the only one. Could you please upload 1.12.2 compatibility ? Thx :)

**Comment by xJiggo** [comment]
This mod may not be added to 1.12.2 but here's an alternative:
https://www.curseforge.com/minecraft/mc-mods/finite-water-control

**Comment by Felicis** [comment]
Principally it comes down to two main points:
1. The (main) 1.16 version is not completely functional yet, therefore I don't see the point to downgrade (or upgrade it) until the design is fully stable and working
2. downgrading a mod (software in general) is always harder and requires more manual work than upgrading
In summary: I'm confident it can be downgraded and I would like to downgrade it, but first I have to finish the 1.16 version, then upgrade to 1.17 and 1.18 and only then I will start working on 1.12. If someone wishes to help we might get there faster :wink:
