### ISSUE TITLE
compatibility with mod tfc( terrafirmacraft 1 18 2)

### ISSUE THREAD

**Issue by py-official** [Felicis/Water-Physics-Overhaul#37]
Hello, can you add compatibility with mod tfc( terrafirmacraft 1 18 2)

I try to use bucket and my client have crashed

[crash-2023-09-29_18.20.28-client.txt](https://github.com/Felicis/Water-Physics-Overhaul/files/12768583/crash-2023-09-29_18.20.28-client.txt)

**Comment by xJiggo** [comment]
There are a few mod compatibility issues with this mod but at the moment he is focusing on fixing water-logging problems and some other related problems before anything else check here #2

**Comment by Felicis** [comment]
exactly, thanks @xJiggo
