### ISSUE TITLE
(Idea) Put on Curseforge

### ISSUE THREAD

**Issue by xJiggo** [Felicis/Water-Physics-Overhaul#47]
Just an idea but if you want add this mod to Curseforge as its easy to keep up to date with latest updates on the mod

**Comment by ChristopherJ123** [comment]
Also put it on modrinth aswell

**Comment by Felicis** [comment]
Maybe it's time to do that... I've always been wary for more publicity, because the mod is far from polished and I don't have a lot of time to work on it :sweat_smile:
