### ISSUE TITLE
Particles keep playing when I remove water

### ISSUE THREAD

**Issue by aeluabik** [Felicis/Water-Physics-Overhaul#9]
Whenever I remove water, some splashing particles keep playing above the water blocks. Tried to understand if it was a mod, but it doesn't seems to be related to effective and visuality. It is pretty annoying, I was looking for a solution to just disable this particle, but no success

**Comment by Yanosiq** [comment]
Yeah i had the same problem

**Comment by aeluabik** [comment]
Seems like it actually was related to effective, but together with something else. Removing it solved the issue
